# Generated by Django 3.2.11 on 2022-01-30 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='to_acno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='api.userprofile'),
        ),
    ]
